version: "3.9"

services:
  web:
    container_name: lara6-web
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - app
      - db
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/log/nginx:/var/log/nginx
    restart: always
  app:
    container_name: lara6-app
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
    restart: always
  db:
    image: mysql:8.0
    container_name: lara6-db
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techboost
      MYSQL_USER: daisuke
      MYSQL_PASSWORD: daisuke!
      TZ: Asia/Tokyo
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
